
name: bd-sig-action 

on:
  push:
    branches: [ sarif-test ]
jobs:
  build:
    runs-on: [ mac ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
          
      - name: Black Duck Full Scan
        if: ${{ github.event_name != 'pull_request' }}
        uses: synopsys-sig/synopsys-action@SIGINT-1189
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
          DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
        with:
          BlaCkDucK_UrL: ${{ secrets.BLACKDUCK_URL_US03 }}
          BlaCkdUck_aPITokEn: ${{ secrets.BLACKDUCK_API_TOKEN_US03 }}
          blackduck_scan_full: true
          reports_sarif_create: true
          reports_sarif_file_path: '/Users/spurohit/.bridge/polaris_results.sarif.json'
          github_token: ${{ secrets.GITHUB_TOKEN }}
