name: bd-sig-action 

on:
  push:
    branches: [ main, master, develop, stage, release, sarif-upload ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
jobs:
  build:
    runs-on: [ mac ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: /Users/spurohit/.bridge/SAST_SARIF.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          # category: my-analysis-tool
