
name: bd-sig-action 

on:
  push:
    branches: [ sarif-test ]
jobs:
  build:
    runs-on: [ mac ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
           
      - name: Black Duck Full Scan
        if: ${{ github.event_name != 'pull_request' }}
        uses: synopsys-sig/synopsys-action@SIGINT-1493
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
          DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
        with:
          synopsys_bridge_download_url: https://artifactory.internal.synopsys.com/artifactory/clops-local/clops.sig.synopsys.com/synopsys-bridge/latest/synopsys-bridge-macos_arm.zip
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackduck_reports_sarif_create: true # Create Black Duck sarif report and upload it as artifact
          blackduck_upload_sarif_report: true  # Upload Black Duck sarif report in GitHub Advanced Security tab
          # blackduck_reports_sarif_groupSCAIssues: true # by default true
          blackduck_reports_sarif_severities: 'CRITICAL,HIGH'
          # blackduck_reports_sarif_file_path: '/Users/spurohit/code/github/tmp' # File path including file name where SARIF report should be created(need to include file name as well)
          github_token: ${{ secrets.GITHUB_TOKEN }} # Mandatory if blackduck_upload_sarif_report is set as true
