name: security-scan 
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]  
jobs:
  polaris-scan:
    runs-on: [ mac ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Black Duck Scan
        uses: synopsys-sig/synopsys-action@SIGINT-1301
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        with:
          bridge_download_url: ${{ secrets.INTERNAL_ARTIFACTORY_URL }}/2.0.7/synopsys-bridge-2.0.7-macosx.zip
          coverity_url: ${{ secrets.COVERITY_URL }}
          coverity_user: ${{ secrets.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          coverity_project_name: ${{ secrets.COVERITY_PROJECT_NAME }}
          coverity_automation_prcomment: true
          # polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN_PIM }}
          # reports_sarif_create: true
          # reports_sarif_file_path: /Users/spurohit/.bridge/SAST_SARIF.sarif
          # upload_sarif_result: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
