name: security-scan 
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]  
jobs:
  polaris-scan:
    runs-on: [ mac ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16  
      - name: Black Duck Scan
        uses: synopsys-sig/synopsys-action@SIGINT-1236
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        with:
          # synopsys_bridge_download_url: https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-bridge/2.0.0/synopsys-bridge-2.0.0-macosx.zip
          # synopsys_bridge_download_version: 2.0.0
          blackduck_url: ${{ secrets.BLACKDUCK_URL_US03 }}
          blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN_US03 }}
          # polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN_PIM }}
          # reports_sarif_create: true
          # reports_sarif_file_path: /Users/spurohit/.bridge/SAST_SARIF.sarif
          # upload_sarif_result: true
          # github_token: ${{ secrets.GITHUB_TOKEN }}
