name: security-scan 
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]  
jobs:
  polaris-scan:
    runs-on: [ mac ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3steps:
      - name: setp node
        uses: actions/setup-node@v3
        with:
          node-version: 16  
      - name: Black Duck Scan
        uses: synopsys-sig/synopsys-action@SIGINT-1237
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        with:
          blackduck_url: ${{ secrets.BLACKDUCK_URL_US03 }}
          blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN_US03 }}
          blackduck_fixpr_enabled: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
