name: security-scan 
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]  
jobs:
  blackduck-scan:
    runs-on: [ mac ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Black Duck Scan
        uses: synopsys-sig/synopsys-action@SIGINT-1409
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          BLACKDUCK_TRUST_CERT: true
        with:
          # bridge_download_url: ${{ secrets.INTERNAL_ARTIFACTORY_URL }}/2.0.30/synopsys-bridge-2.0.30-macosx.zip
          # synopsys_bridge_download_version: 2.0.0
          BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL_VIN }}
          blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN_VIN }}
          # blackduck_fixpr_enabled: true
          # reports_sarif_create: true
          # reports_sarif_file_path: /Users/spurohit/.bridge/SAST_SARIF.sarif
          # upload_sarif_result: true
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          # include_diagnostics: true
