name: bd-sig-action 

on:
  push:
    branches: [ main, master, develop, stage, release, sarif-upload ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
jobs:
  build:
    runs-on: [ mac ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      # - name: Black Duck Full Scan
      #   if: ${{ github.event_name != 'pull_request' }}
      #   uses: synopsys-sig/synopsys-action@main
      #   env:
      #     DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
      #     DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
      #     DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
      #   with:
      #     BlaCkDucK_UrL: ${{ secrets.BLACKDUCK_URL }}
      #     BlaCkdUck_aPITokEn: ${{ secrets.BLACKDUCK_API_TOKEN }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: /Users/spurohit/.bridge/results.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          # category: my-analysis-tool
