
name: bd-sig-action 

on:
  push:
    branches: [ sarif-test ]
jobs:
  build:
    runs-on: [ mac ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
           
      - name: Black Duck Full Scan
        if: ${{ github.event_name != 'pull_request' }}
        uses: synopsys-sig/synopsys-action@SIGINT-1189
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
          DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
        with:
          synopsys_bridge_download_url: https://artifactory.internal.synopsys.com/artifactory/clops-local/clops.sig.synopsys.com/synopsys-bridge/latest/synopsys-bridge-macos_arm.zip
          BlaCkDucK_UrL: ${{ secrets.BLACKDUCK_URL }}
          BlaCkdUck_aPITokEn: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackduck_reports_sarif_create: true
          upload_sarif_result: true
          # reports_sarif_file_path: '/Users/spurohit/.bridge/polaris_results.sarif.json'
          github_token: ${{ secrets.GITHUB_TOKEN }}
