
name: bd-sig-action

on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:  
jobs:
  build:
    runs-on: [ mac ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
#       - name: Setup Java JDK
#         uses: actions/setup-java@v3
#         with:
#           java-version: 17
#           distribution: microsoft
#           cache: maven  
        
#       - name: Coverity Full Scan
#         if: ${{ github.event_name != 'pull_request' }}
#         uses: synopsys-sig/synopsys-action@main
#         with:
#           coverity_url: ${{ secrets.COVERITY_URL }}
#           coverity_user: ${{ secrets.COVERITY_USER }}
#           coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
#           coverity_project_name: ${{ github.event.repository.name }}
#           coverity_stream_name: ${{ github.event.repository.name }}-${{ github.ref_name }}
#           coverity_policy_view: 'Outstanding Issues'  
#           include_diagnostics: true  

      - name: Black Duck Full Scan
        if: ${{ github.event_name != 'pull_request' }}
        uses: synopsys-sig/synopsys-action@SIGINT-994
        ### Use below configurations to set specific detect environment varibales
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
          DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
        with:
#           network_air_gap: "kdka"
#           synopsys_bridge_path: "/Users/spurohit/airgap-testing"
#           synopsys_bridge_install_directory: "/Users/spurohit/airgap-testing"
#           bridge_download_url: "https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-bridge/0.3.59/synopsys-bridge-0.3.59-macosx.zip"
#           bridge_download_version: "0.3.1"
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackduck_scan_full: true
          BLACKDUCK_TRUST_CERT: true
          ### Accepts Multiple Values
          blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
          ### Uncomment below configuration to enable autoamtic fix pull request creation if vulnerabilities are reported
#           blackduck_automation_fixpr: true 
#           github_token: ${{ secrets.GITHUB_TOKEN }} # Mandatory when blackduck_automation_fixpr is set to 'true'
          ### Uncomment below configuration if Synopsys Bridge diagnostic files needs to be uploaded
          # include_diagnostics: true  

#       - name: Black Duck PR Scan
#         if: ${{ github.event_name == 'pull_request' }}
#         uses: synopsys-sig/synopsys-action@v1.2.0
#         ### Use below configurations to set specific detect environment varibales
#         env:
#           DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
#           DETECT_PROJECT_VERSION_NAME: ${{ github.base_ref }}
#           DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.base_ref }}
#         with:
#           blackduck_url: ${{ secrets.BLACKDUCK_URL }}
#           blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN }}
#           blackduck_scan_full: false
#           ### Below configuration is used to enable automatic pull request comment based on Black Duck scan result
#           blackduck_automation_prcomment: true
#           github_token: ${{ secrets.GITHUB_TOKEN }} # Mandatory when blackduck_automation_prcomment is set to 'true'
#           ### Uncomment below configuration if Synopsys Bridge diagnostic files needs to be uploaded
#           # include_diagnostics: true
