  name: Synopsys-Actions
  # Controls when the workflow will run
  on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

    
    workflow_dispatch:
  jobs:
    build:
      runs-on: [ mac ]

      steps:
        - name: Checkout Source
          uses: actions/checkout@v3

        - name: Black Duck Full Scan
          if: ${{ github.event_name != 'pull_request' }}
          uses: synopsys-sig/synopsys-action@v1.2.0
          ### Use below configurations to set specific detect environment varibales
          env: 
            DETECT_PROJECT_NAME: "Blackduck-Synopsys-Action-Example-NodeJS-Webgoat"
            DETECT_PROJECT_VERSION_NAME: "1.0"
            DETECT_TOOLS_EXCLUDED: 'SIGNATURE_SCAN'
            BLACKDUCK_TRUST_CERT: true
            DETECT_PROJECT_APPLICATION_ID: '248982' 
            DETECT_PROJECT_TAGS: "bottomzone,contractors,internal,nexus,nonmodifiedoss,notdistributed,weboat"
            DETECT_WAIT_FOR_RESULTS: true
          with:
            BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL }}
            BLACKDUCK_APITOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
            # blackduck_scan_full: true
            ### Accepts Multiple Values
            # blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
            ### Uncomment below configuration to enable autoamtic fix pull request creation if vulnerabilities are reported
            # blackduck_automation_fixpr: true 
            # github_token: ${{ secrets.GITHUB_TOKEN }} # Mandatory when blackduck_automation_fixpr is set to 'true'
            ### Uncomment below configuration if Synopsys Bridge diagnostic files needs to be uploaded
            # include_diagnostics: true 

        - name: Black Duck PR Scan
          if: ${{ github.event_name == 'pull_request' }}
          uses: synopsys-sig/synopsys-action@v1.2.0
          with:
            BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL }}
            BLACKDUCK_APITOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
            #blackduck_automation_fixpr: true
            # blackduck_scan_full: false
            # blackduck_automation_prcomment: true
            # github_token: ${{ secrets.PAT }}
            #  include_diagnostics: true
          env: 
            DETECT_PROJECT_NAME: "Blackduck-Synopsys-Action-Example-NodeJS-Webgoat"
            DETECT_PROJECT_VERSION_NAME: "1.0"
            DETECT_TOOLS_EXCLUDED: 'SIGNATURE_SCAN'
            BLACKDUCK_TRUST_CERT: true
            DETECT_PROJECT_APPLICATION_ID: '248982' 
            DETECT_PROJECT_TAGS: "bottomzone,contractors,internal,nexus,nonmodifiedoss,notdistributed,weboat"
            DETECT_WAIT_FOR_RESULTS: true 
