name: Synopsys-Actions
on:
  push:
    branches: 
    - master
  pull_request:
    types: [blackduck_automation_fixpr]
    branches:
    - master
  pull_request_review_comment:
    types: [blackduck_automation_fixpr]
    branches:
    - master
   
  workflow_dispatch:
jobs:
  build:
    runs-on: [ ubuntu-latest ]    
    strategy:
      matrix:
        node-version: [16.19.0]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm run build --if-present
    
    - name: install java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    # - name: Update GITHUB_PATH
    #   run: |
    #     echo "HOME=/home/ghrunner" >> $GITHUB_ENV
    
    - name: Synopsys Detect
      id: blackduck
      uses: synopsys-sig/synopsys-action@v1.2.0
      with:
         blackduck_url: ${{ secrets.BLACKDUCK_URL }}
         blackduck_apitoken: ${{ secrets.BLACKDUCK_API_TOKEN }}
         blackduck_automation_fixpr: true
         blackduck_scan_full: true
         blackduck_automation_prcomment: true
         github_token: "${{secrets.GITHUB_TOKEN}}"

      
      env: 
         DETECT_PROJECT_NAME: "Blackduck-Synopsys-Action-Example-NodeJS"
         DETECT_PROJECT_VERSION_NAME: ${GITHUB_RUN_NUMBER}
         DETECT_TOOLS_EXCLUDED: 'SIGNATURE_SCAN'
         BLACKDUCK_TRUST_CERT: true
         DETECT_PROJECT_APPLICATION_ID: '248981' 
         DETECT_PROJECT_TAGS: "bottomzone,contractors,internal,nexus,nonmodifiedoss,notdistributed"
         DETECT_WAIT_FOR_RESULTS: true
#          DETECT_TIMEOUT: 600