name: detect-action
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
jobs:
  build:
    runs-on: [ mac ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3  
      - name: Run Synopsys Detect
        uses: synopsys-sig/detect-action@v0.3.3
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            detect-version: 8.2.0
            blackduck-url: ${{ secrets.BLACKDUCK_URL_US03 }}
            blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN_US03 }}  
            scan-mode: RAPID
